services:
  db:
    image: postgres:15
    container_name: nestly-db
    environment:
      POSTGRES_DB: nestly
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - nestly-data:/var/lib/postgresql/data

volumes:
  nestly-data:
